//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class DefaultSceneManagerFactory : SceneManagerFactory {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DefaultSceneManagerFactory(global::System.IntPtr cPtr, bool cMemoryOwn) : base(OgrePINVOKE.DefaultSceneManagerFactory_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DefaultSceneManagerFactory obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DefaultSceneManagerFactory() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgrePINVOKE.delete_DefaultSceneManagerFactory(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public DefaultSceneManagerFactory() : this(OgrePINVOKE.new_DefaultSceneManagerFactory(), true) {
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public static string FACTORY_TYPE_NAME {
    get {
      string ret = OgrePINVOKE.DefaultSceneManagerFactory_FACTORY_TYPE_NAME_get();
      if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SceneManager createInstance(string instanceName) {
    global::System.IntPtr cPtr = OgrePINVOKE.DefaultSceneManagerFactory_createInstance(swigCPtr, instanceName);
    SceneManager ret = (cPtr == global::System.IntPtr.Zero) ? null : new SceneManager(cPtr, false);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public override void destroyInstance(SceneManager instance) {
    OgrePINVOKE.DefaultSceneManagerFactory_destroyInstance(swigCPtr, SceneManager.getCPtr(instance));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
