//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class DefaultPlaneBoundedVolumeListSceneQuery : PlaneBoundedVolumeListSceneQuery {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal DefaultPlaneBoundedVolumeListSceneQuery(global::System.IntPtr cPtr, bool cMemoryOwn) : base(OgrePINVOKE.DefaultPlaneBoundedVolumeListSceneQuery_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DefaultPlaneBoundedVolumeListSceneQuery obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DefaultPlaneBoundedVolumeListSceneQuery() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgrePINVOKE.delete_DefaultPlaneBoundedVolumeListSceneQuery(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public DefaultPlaneBoundedVolumeListSceneQuery(SceneManager creator) : this(OgrePINVOKE.new_DefaultPlaneBoundedVolumeListSceneQuery(SceneManager.getCPtr(creator)), true) {
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public override void execute(SceneQueryListener listener) {
    OgrePINVOKE.DefaultPlaneBoundedVolumeListSceneQuery_execute(swigCPtr, SceneQueryListener.getCPtr(listener));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
