//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum OrientationMode {
  OR_DEGREE_0 = 0,
  OR_DEGREE_90 = 1,
  OR_DEGREE_180 = 2,
  OR_DEGREE_270 = 3,
  OR_PORTRAIT = OR_DEGREE_0,
  OR_LANDSCAPERIGHT = OR_DEGREE_90,
  OR_LANDSCAPELEFT = OR_DEGREE_270
}

}
