//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum RenderQueueGroupID {
  RENDER_QUEUE_BACKGROUND = 0,
  RENDER_QUEUE_SKIES_EARLY = 5,
  RENDER_QUEUE_1 = 10,
  RENDER_QUEUE_2 = 20,
  RENDER_QUEUE_WORLD_GEOMETRY_1 = 25,
  RENDER_QUEUE_3 = 30,
  RENDER_QUEUE_4 = 40,
  RENDER_QUEUE_MAIN = 50,
  RENDER_QUEUE_6 = 60,
  RENDER_QUEUE_7 = 70,
  RENDER_QUEUE_WORLD_GEOMETRY_2 = 75,
  RENDER_QUEUE_8 = 80,
  RENDER_QUEUE_9 = 90,
  RENDER_QUEUE_SKIES_LATE = 95,
  RENDER_QUEUE_OVERLAY = 100,
  RENDER_QUEUE_MAX = 105
}

}
