//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public enum SceneType {
  ST_GENERIC = 1,
  ST_EXTERIOR_CLOSE = 2,
  ST_EXTERIOR_FAR = 4,
  ST_EXTERIOR_REAL_FAR = 8,
  ST_INTERIOR = 16
}

}
