//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace org.ogre {

public class TextureUnitStates : global::System.IDisposable, global::System.Collections.IEnumerable
    , global::System.Collections.Generic.IList<TextureUnitState>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TextureUnitStates(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TextureUnitStates obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~TextureUnitStates() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OgrePINVOKE.delete_TextureUnitStates(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public TextureUnitStates(global::System.Collections.ICollection c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (TextureUnitState element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public TextureUnitState this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(TextureUnitState[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(TextureUnitState[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, TextureUnitState[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  global::System.Collections.Generic.IEnumerator<TextureUnitState> global::System.Collections.Generic.IEnumerable<TextureUnitState>.GetEnumerator() {
    return new TextureUnitStatesEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new TextureUnitStatesEnumerator(this);
  }

  public TextureUnitStatesEnumerator GetEnumerator() {
    return new TextureUnitStatesEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class TextureUnitStatesEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<TextureUnitState>
  {
    private TextureUnitStates collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public TextureUnitStatesEnumerator(TextureUnitStates collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public TextureUnitState Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (TextureUnitState)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    OgrePINVOKE.TextureUnitStates_Clear(swigCPtr);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(TextureUnitState x) {
    OgrePINVOKE.TextureUnitStates_Add(swigCPtr, TextureUnitState.getCPtr(x));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = OgrePINVOKE.TextureUnitStates_size(swigCPtr);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = OgrePINVOKE.TextureUnitStates_capacity(swigCPtr);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    OgrePINVOKE.TextureUnitStates_reserve(swigCPtr, n);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public TextureUnitStates() : this(OgrePINVOKE.new_TextureUnitStates__SWIG_0(), true) {
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public TextureUnitStates(TextureUnitStates other) : this(OgrePINVOKE.new_TextureUnitStates__SWIG_1(TextureUnitStates.getCPtr(other)), true) {
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public TextureUnitStates(int capacity) : this(OgrePINVOKE.new_TextureUnitStates__SWIG_2(capacity), true) {
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  private TextureUnitState getitemcopy(int index) {
    global::System.IntPtr cPtr = OgrePINVOKE.TextureUnitStates_getitemcopy(swigCPtr, index);
    TextureUnitState ret = (cPtr == global::System.IntPtr.Zero) ? null : new TextureUnitState(cPtr, false);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private TextureUnitState getitem(int index) {
    global::System.IntPtr cPtr = OgrePINVOKE.TextureUnitStates_getitem(swigCPtr, index);
    TextureUnitState ret = (cPtr == global::System.IntPtr.Zero) ? null : new TextureUnitState(cPtr, false);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, TextureUnitState val) {
    OgrePINVOKE.TextureUnitStates_setitem(swigCPtr, index, TextureUnitState.getCPtr(val));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(TextureUnitStates values) {
    OgrePINVOKE.TextureUnitStates_AddRange(swigCPtr, TextureUnitStates.getCPtr(values));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public TextureUnitStates GetRange(int index, int count) {
    global::System.IntPtr cPtr = OgrePINVOKE.TextureUnitStates_GetRange(swigCPtr, index, count);
    TextureUnitStates ret = (cPtr == global::System.IntPtr.Zero) ? null : new TextureUnitStates(cPtr, true);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, TextureUnitState x) {
    OgrePINVOKE.TextureUnitStates_Insert(swigCPtr, index, TextureUnitState.getCPtr(x));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, TextureUnitStates values) {
    OgrePINVOKE.TextureUnitStates_InsertRange(swigCPtr, index, TextureUnitStates.getCPtr(values));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    OgrePINVOKE.TextureUnitStates_RemoveAt(swigCPtr, index);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    OgrePINVOKE.TextureUnitStates_RemoveRange(swigCPtr, index, count);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public static TextureUnitStates Repeat(TextureUnitState value, int count) {
    global::System.IntPtr cPtr = OgrePINVOKE.TextureUnitStates_Repeat(TextureUnitState.getCPtr(value), count);
    TextureUnitStates ret = (cPtr == global::System.IntPtr.Zero) ? null : new TextureUnitStates(cPtr, true);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    OgrePINVOKE.TextureUnitStates_Reverse__SWIG_0(swigCPtr);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    OgrePINVOKE.TextureUnitStates_Reverse__SWIG_1(swigCPtr, index, count);
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, TextureUnitStates values) {
    OgrePINVOKE.TextureUnitStates_SetRange(swigCPtr, index, TextureUnitStates.getCPtr(values));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(TextureUnitState value) {
    bool ret = OgrePINVOKE.TextureUnitStates_Contains(swigCPtr, TextureUnitState.getCPtr(value));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int IndexOf(TextureUnitState value) {
    int ret = OgrePINVOKE.TextureUnitStates_IndexOf(swigCPtr, TextureUnitState.getCPtr(value));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int LastIndexOf(TextureUnitState value) {
    int ret = OgrePINVOKE.TextureUnitStates_LastIndexOf(swigCPtr, TextureUnitState.getCPtr(value));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Remove(TextureUnitState value) {
    bool ret = OgrePINVOKE.TextureUnitStates_Remove(swigCPtr, TextureUnitState.getCPtr(value));
    if (OgrePINVOKE.SWIGPendingException.Pending) throw OgrePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
